// @AbapCatalog.sqlViewName: 'P_ITEMS'
// @AbapCatalog.preserveKey:true
// @ClientHandling.type : #INHERITED
// @ClientHandling.algorithm : #AUTOMATED
@VDM.private: true
@VDM.viewType: #BASIC
// @AbapCatalog.compiler.compareFilter: true
@ObjectModel.usageType: {serviceQuality: #B, sizeCategory: #XL, dataClass: #TRANSACTIONAL}
@AccessControl.authorizationCheck: #NOT_REQUIRED
@VDM.lifecycle.contract.type: #NONE
define view entity YI_PP_BOMItemsAPIWrap
  as select from P_BOMItems
{
  key BillOfMaterialCategory,
  key BillOfMaterial,
  key BillOfMaterialVariant,
  key BillOfMaterialItemNodeNumber,
      BillOfMaterialItemUUID,
      BOMItemInternalChangeCount,
      InheritedNodeNumberForBOMItem,
      InheritedNodeNumberVersionBOM,
      BillOfMaterialVersion,
      @Semantics.businessDate.from: true
      ValidityStartDate,
      @Semantics.businessDate.to: true
      ValidityEndDate,
      ChangeNumberFrom,
      ChangeNumberTo,
      BOMItemRecordCreationDate,
      BOMItemCreatedByUser,
      BOMItemLastChangeDate,
      BOMItemLastChangedByUser,
      BillOfMaterialComponent,
      BillOfMaterialItemCategory,
      BillOfMaterialItemNumber,
      // @Semantics.unitOfMeasure: true
      BillOfMaterialItemUnit,
      @Semantics.quantity.unitOfMeasure: 'BillOfMaterialItemUnit'
      BillOfMaterialItemQuantity,
      IsSubItem,
      SortString,
      BOMItemSorter,
      FixedQuantity,
      BOMItemHasFixedQuantity,
      PurchasingGroup,
      // @Semantics.currencyCode: true
      Currency,
      @Semantics.amount.currencyCode : 'Currency'
      MaterialComponentPrice,
      MaterialPriceUnitQty,
      ComponentScrapInPercent,
      OperationScrapInPercent,
      IsNetScrap,
      NumberOfVariableSizeItem,
      QuantityVariableSizeItem,
      FormulaKey,
      BOMItemDescription,
      BOMItemText2,
      LongTextLanguage,
      MaterialGroup,
      DocumentType,
      DocNumber,
      DocumentVersion,
      DocumentPart,
      ClassNumber,
      ClassType,
      ResultingItemCategory,
      DependencyObjectNumber,
      ObjectType,
      IsClassificationRelevant,
      IsBulkMaterial,
      BOMItemIsSparePart,
      BOMItemIsSalesRelevant,
      IsProductionRelevant,
      BOMItemIsPlantMaintRelevant,
      BOMItemIsCostingRelevant,
      IsEngineeringRelevant,
      SpecialProcurementType,
      IsBOMRecursiveAllowed,
      OperationLeadTimeOffset,
      OpsLeadTimeOffsetUnit,
      BOMItemChangeDate,
      IsMaterialProvision,
      BOMIsRecursive,
      DocumentIsCreatedByCAD,
      DistrKeyCompConsumption,
      DeliveryDurationInDays,
      Creditor,
      CostElement,
      Size1,
      Size2,
      Size3,
      UnitOfMeasureForSize1To3,
      GoodsReceiptDuration,
      PurchasingOrganization,
      RequiredComponent,
      MultipleSelectionAllowed,
      ProdOrderIssueLocation,
      MaterialIsCoProduct,
      ExplosionType,
      FollowUpGroup,
      DiscontinuationGroup,
      ReinsurContrOrgUnit,
      IsConfigurableBOM,
      ReferencePoint,
      LeadTimeOffset,
      IsSoftwareComponent,
      ProductionSupplyArea,
      IsDeleted,
      IsALE,
      UnitOfMeasureForPiece,
      UnitOfMeasureForVarSizeItem,
      AlternativeItemGroup,
      AlternativeItemPriority,
      AlternativeItemStrategy,
      UsageProbabilityPercent,
      IsPMAssemblyRelevant,
      IsAssembly,
      IsPhantomItem,
      SpclProcmtTypeIsConsistent,
      LastChangeDateTime,
      OrigSalesOrderBOMItmCategory,
      OrigSalesOrderBOM,
      OrigSalesOrderBOMItmNodeNumber,
      OrigSalesOrderBOMItmNumber,
      PreliminaryMaterial
}